SELECT
	A.EmployeeKey,
	B.NOME,
	A.Ano,
	A.Total_Vendas
FROM(
	SELECT * FROM V_PQ_VENDAS_ATE_2012
	UNION ALL
	SELECT * FROM V_PQ_VENDAS_DEPOIS_2012
	) A
LEFT JOIN V_PQ_PESSOAS B
ON A.EmployeeKey = B.ID
